# Main config
destination:  ./_site

# Site info
name: Snowsport for Sheffield

# We don't want to publish some files
exclude: [
  '_scss',
  'node_modules',
  '.gitignore',
  'Gemfile',
  'Gemfile.lock',
  'gruntfile.js',
  'package.json',
  'README.md'
]