# Main config
destination:  ./_site

# Site info
name: Snowsport for Sheffield

url: http://timble.github.io/www.snowsportforsheffield.co.uk

# We don't want to publish some files
exclude: [
  '_scss',
  'node_modules',
  'bower_components',
  '.gitignore',
  'bower.json',
  'Gemfile',
  'Gemfile.lock',
  'gruntfile.js',
  'package.json',
  'README.md'
]